name: Go Linter
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  golangci:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          go-version-file: "go.mod"
          cache: true
          version: v2.1
          only-new-issues: true
